check: []
build:
  build-strategy: Source
  base-image: registry.access.redhat.com/ubi8/nodejs-16:latest
  registry: quay.io
  registry-org: open-services-group
  registry-project: peribolos-as-a-service
  registry-secret: osg-pusher-secret
deploy:
  project-org: open-services-group
  project-name: peribolos-as-a-service
  image-name: peribolos-service-controller
