name: Build Peribolos
description: Build Peribolos container from ./peribolos-fix/Dockerfile
inputs:
  tags:
    type: string
    default: ${{ github.sha }}
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      uses: redhat-actions/buildah-build@v2
      with:
        image: peribolos
        tags: "${{ inputs.tags }}"
        context: peribolos-fix
        containerfiles: peribolos-fix/Dockerfile
