---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configurations:
- .transformers.yaml
generators:
- .ksops.yaml
namespace: peribolos-as-a-service-stage
images:
- name: quay.io/open-services-group/peribolos-as-a-service
  newTag: v1.0.0
- name: quay.io/open-services-group/peribolos
  newTag: v1.0.0
