---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configurations:
  - .transformers.yaml
generators:
  - .ksops.yaml
namespace: peribolos-as-a-service-stage
images:
  - name: quay.io/open-services-group/peribolos-as-a-service
    newTag: v0.0.1
  - name: quay.io/open-services-group/peribolos
    newTag: v0.0.1
